---
- hosts: all
  tasks:
   - name: Create Cloudfront ditsribution
     cloudfront_distribution:
        state: present
        origins:
            - id: "S3-{{ bucket_name }}"
              domain_name: "{{ bucket_name }}.s3.amazonaws.com"
              origin_path: ''
              s3_origin_access_identity_enabled: yes
        default_cache_behavior:
              target_origin_id: "S3-{{ bucket_name }}"
